# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
