# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_myuser_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('wind', models.IntegerField()),
                ('rain', models.CharField(max_length=30)),
            ],
        ),
    ]
