# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0004_auto_20170609_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.CharField(blank=True, choices=[('Light rain', 'Light rain'), ('Heavy rain', 'Heavy rain'), ('No rain', 'No rain')], max_length=30, null=True),
        ),
    ]
