# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0005_auto_20170609_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weather',
            name='max_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='min_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.FloatField(),
        ),
    ]
